version: '3'
networks: 
  keycloak-network:
    driver: bridge

services:
  keycloak:
    image: jboss/keycloak:latest
    networks:
      - keycloak-network
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    volumes:
      - /Users/admin/data:/dataexport
