version: '3'
networks: 
  keycloak-network:
    driver: bridge

services:
  mysql:
    image: mysql:latest
    networks:
      - keycloak-network
    environment:
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password 
      MYSQL_ROOT_PASSWORD: root_password 

  keycloak:
    image: jboss/keycloak:latest
    networks:
      - keycloak-network
    depends_on:
      - mysql
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    volumes:
      - ~/data:/dataexport
